language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
# safelist
branches:
  only:
  - develop
#  - master

#script:
#  - pytest

# for heroku deployment:
# https://docs.travis-ci.com/user/deployment/heroku/